name: iw4p_proxy-scraper-http

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

env:
  style: http
  filename: iw4p
  
jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proxy repo
        uses: actions/checkout@v3
        with:
          repository: iw4p/proxy-scraper

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: gather proxy
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python proxyScraper.py -p ${style} -o proxy.txt
          python proxyChecker.py -t 20 -s bing.com -l proxy.txt
          python proxyChecker.py -t 20 -s ifconfig.me -l proxy.txt

      - name: upload file
        run: |
          wget https://raw.githubusercontent.com/Eloco/free-proxy-raw/main/.github/github_upload.py -O github_upload.py
          python -m pip install fire
          python -m pip install pipreqs
          pipreqs .
          python -m pip install -r requirements.txt
          python github_upload.py --repo "${{ github.repository }}" --filename "proxy/${style}_$(date +%s)_${filename}_C$(cat proxy.txt | wc -l).txt" --content "proxy.txt" --token "${{ secrets.GITHUB_TOKEN }}"

