name: tor_test_playwright

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url to test'
        required: false
        default: "https://froxy.com/api/detect-ip/"
      browserType:
        description: 'default firefox (chromium or webkit)'
        required: false
        default: "firefox"
      sleep:
        description: 'sleep seconds'
        required: false
        default: "30"

env:
  url: ${{ github.event.inputs.url }}
  browserType: ${{ github.event.inputs.browserType }}
  sleep: ${{ github.event.inputs.sleep }}

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Build and Run containers
        run: |
              wget https://raw.githubusercontent.com/CECNdata/GA-pub/main/.github/.torrc -O torrc
              docker run -it --name tor -p 8118:8118 -p 9050:9050 -v $(pwd)/torrc:/etc/tor/torrc:ro -d dperson/torproxy 
              timeout 2m bash -c -- 'while [[ `docker logs tor --tail 1 2>&1` != *"Bootstrapped 100"* ]]; do (sleep 5;docker logs tor --tail 1 2>&1);done ' || (docker rm -f tor;docker run -it --name tor -p 8118:8118 -p 9050:9050 -v $(pwd)/torrc:/etc/tor/torrc:ro -d dperson/torproxy); sleep 10
              
      - name: Install Playwright
        run: |
            python -m pip install playwright html2text
            npx playwright install-deps $browserType
            python -m playwright install $browserType
            wget https://raw.githubusercontent.com/Eloco/free-proxy-raw/main/.github/proxy_test.py -O proxy_test.py
      - name: check ip
        run: |
              curl -Ls https://github.com/ipinfo/cli/releases/download/ipinfo-2.8.1/deb.sh | sh
              ipinfo `curl -sx 127.0.0.1:8118 ifconfig.me`
      - name: proxy test
        run: |
          export proxy='http://127.0.0.1:8118'
          timeout 1800 xvfb-run python proxy_test.py
          cat page.html | html2text
      - uses: actions/upload-artifact@v3
        with:
          name: dl-html
          path: page.html # or path/to/artifact
